# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5a5c02b7faa4e70789db92b7230ef1a0a9461ab6dc4eddc8736c2640c74af4d6413fcebb839bd283b43169383bd8eacd81a473077ee81028f281b865fdc80ff

test:
  secret_key_base: 5e1fec6f962414ab5f31b4c4a17ae0c314e13c5374437eaf7b920b5dbca36ffd5c1f0b1fc1a71e1c0f621465065b61a824ab7b905d3c718d36e2457f29b44e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
